version: 2.0.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    dotnet restore src/HomeAutio.Mqtt.GoogleHome.sln

    dotnet publish -c Release src/HomeAutio.Mqtt.GoogleHome.sln
test:
  categories:
    except:
    - Integration
artifacts:
- path: src\HomeAutio.Mqtt.GoogleHome\bin\$(configuration)\net5.0\publish
  name: HomeAutio.Mqtt.GoogleHome-$(appveyor_build_version)
deploy:
- provider: GitHub
  auth_token: $(GITHUB_API_KEY)
  artifact: src\HomeAutio.Mqtt.GoogleHome\bin\$(configuration)\net5.0\HomeAutio.Mqtt.GoogleHome-$(appveyor_build_version).zip