name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNETVERSION: "7.0.x"
  APP: "HomeAutio.Mqtt.GoogleHome"
  SOLUTION: "./src/HomeAutio.Mqtt.GoogleHome.sln"
  BUILDOUTPUTPATH: "./src/HomeAutio.Mqtt.GoogleHome/bin/Release/net7.0"
  REGISTRY: ghcr.io
  DOCKER_NAME: "i8beef/homeautio.mqtt.googlehome"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Get version
        id: version
        run: echo "version-without-v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get previous release tag
        id: previousTag
        run: |
          PREV_REV=$(git rev-list --tags --max-count=1 --skip=1 --no-walk)
          PREV_TAG=$(git describe --tags ${PREV_REV})
          echo "tag=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore /p:Version=${{ steps.version.outputs.version-without-v }}

      - name: Test
        run: dotnet test ${{ env.SOLUTION }} --no-restore --verbosity normal --logger trx --results-directory "TestResults"

      - name: Upload app build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}
          path: ${{ env.BUILDOUTPUTPATH }}

      - name: Upload TestResults build artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults

      - name: ZIP release artifact
        run: zip -r ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}.zip ${{ env.BUILDOUTPUTPATH }}

      - name: GitHub release
        id: release
        run: gh release create ${{ github.ref }} "${{ env.APP }}-${{ steps.version.outputs.version-without-v }}.zip" -t "${{ steps.version.outputs.version-without-v }}" --generate-notes --notes-start-tag ${{ steps.previousTag.outputs.tag }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    needs: release
    strategy:
      matrix:
        include:
          -
            docker-file: "./src/Dockerfile"
            docker-tag: "amd64"
          -
            docker-file: "./src/Dockerfile.arm64"
            docker-tag: "arm64"
          -
            docker-file: "./src/Dockerfile.arm32"
            docker-tag: "arm32"
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Get version
        id: version
        run: echo "version-without-v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version-without-v }}-${{ matrix.docker-tag }}
            type=raw,value=latest-${{ matrix.docker-tag }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ${{ matrix.docker-file }}
          build-args: VERSION=${{ steps.version.outputs.version-without-v }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-publish:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: echo "version-without-v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker images
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-amd64
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-arm32
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-arm64
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-amd64
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-arm32
          docker pull ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-arm64

      - name: Build Docker latest image manifest
        run: |
          docker manifest create \
            ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }} \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-amd64 \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-arm32 \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}-arm64

      - name: Push Docker version image manifest
        run: docker manifest push --purge ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:${{ steps.version.outputs.version-without-v }}

      - name: Build Docker latest image manifest
        run: |
          docker manifest create \
            ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-amd64 \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-arm32 \
            --amend ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest-arm64

      - name: Push Docker latest image manifest
        run: docker manifest push --purge ${{ env.REGISTRY }}/${{ env.DOCKER_NAME }}:latest